<?php
define('DT_REWRITE', true);
require 'config.inc.php';
require '../common.inc.php';
$module='webprice';
require DT_ROOT.'/'.$module.'/common.inc.php';

echo '<!DOCTYPE html>';
echo '<html>';
echo '	<head>';
echo '		<title>电气天下客户端</title>';
echo '		<meta charset="utf-8" />';
echo '		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>';
echo '		<meta content="yes" name="apple-mobile-web-app-capable"/>';
echo '		<meta content="yes" name="apple-touch-fullscreen"/>';
echo '		<meta content="telephone=no" name="format-detection"/>';
echo '		<meta http-equiv="x-rim-auto-match" content="none"> ';
echo '		<meta content="black" name="apple-mobile-web-app-status-bar-style">';
echo '		<meta name="author" content="www.dq123.com" />';
echo '		<meta name="copyright"  content="Copyright &copy;www.dq123.com 版权所有" />';
echo '		<meta name="revisit-after"  content="1 days" />';
echo '		<meta name="keywords" content="" />';
echo '		<meta name="description" content="" />';
echo '		<link rel="apple-touch-icon-precomposed" href="http://www.dq123.com/webprice/images/touch-icon.png" >';
echo '		<link rel="shortcut icon" type="image/x-icon" href="http://www.dq123.com/favicon.ico"/>';
echo '		<link rel="bookmark" type="image/x-icon" href="http://www.dq123.com/favicon.ico"/>';
echo '		<link rel="canonical" href="http://www.dq123.com/webprice/index.html#nocheck" />';
echo '		<script type="text/javascript">';
echo '			var url="'.$url.'";';
echo '			var scale = 1.0, ratio = 1;';
echo '			(function() {';
echo '				if (window.devicePixelRatio === 2 && window.navigator.appVersion.match(/iphone/gi)) {';
echo '					scale = 0.5;';
echo '					ratio = 2;';
echo '				}';
echo '				var text = \'<meta name="viewport" content="initial-scale=\' + scale + \', maximum-scale=\' + scale +\', minimum-scale=\' + scale + \', user-scalable=no" />\'+ \'<link\' + \' type="text/css" rel="styleSheet" href="css/index\'+ratio+\'.css?v=\'+Date.now()+\'"\' + \' />\';';
echo '				document.write(text);';
echo '			})();';
echo '		</script>';
echo '	</head>';
echo '	<body>';
echo '		<div id="downCover" class="down" style="display:none;">';
echo '			<div class="tiparea">';
echo '				<div style="text-align:right;"><img src="images/share_1.png" style="width:120px!important;" /><img src="images/share_2.png" style="width:30px!important;" /></div>';
echo '				<div class="method"><img src="images/share_4.png" /><br/><div>在浏览器中打开</div></div>或者';
echo '				<div class="method"><input id="copyInput" type="text" class="txt" value="'.$url.'"><br/>复制下载地址到其他浏览器中下载</div>';
echo '			</div>';
echo '		</div>';
echo '		<script type="text/javascript">';
echo '				document.addEventListener(\'WeixinJSBridgeReady\', function onBridgeReady() {';
echo '					window.shareData = {';
echo '						"imgUrl": "http://www.dq123.com/webprice/images/touch-icon.png",';
echo '						"timeLineLink": "http://www.dq123.com/webprice/index.html?wxref=mp.weixin.qq.com",';
echo '						"sendFriendLink": "http://www.dq123.com/webprice/index.html?wxref=mp.weixin.qq.com",';
echo '						"weiboLink": "http://www.dq123.com/webprice/index.html?wxref=mp.weixin.qq.com",';
echo '						"tTitle": "电气天下客户端",';
echo '						"tContent": "选型、询价、查样本，么么哒~",';
echo '						"fTitle": "电气天下客户端",';
echo '						"fContent": "选型、询价、查样本，么么哒~",';
echo '						"wContent": "选型、询价、查样本，么么哒~"';
echo '					};';
echo '					/* 发送给好友 */';
echo '					WeixinJSBridge.on(\'menu:share:appmessage\', function (argv) {';
echo '						WeixinJSBridge.invoke(\'sendAppMessage\', {';
echo '							"img_url": window.shareData.imgUrl,';
echo '							"img_width": "640",';
echo '							"img_height": "640",';
echo '							"link": window.shareData.sendFriendLink,';
echo '							"desc": window.shareData.fContent,';
echo '							"title": window.shareData.fTitle';
echo '						}, function (res) {';
echo '							/* _report(\'send_msg\', res.err_msg); */';
echo '						})';
echo '					});';
echo '					/* 分享到朋友圈 */';
echo '					WeixinJSBridge.on(\'menu:share:timeline\', function (argv) {';
echo '						WeixinJSBridge.invoke(\'shareTimeline\', {';
echo '							"img_url": window.shareData.imgUrl,';
echo '							"img_width": "640",';
echo '							"img_height": "640",';
echo '							"link": window.shareData.timeLineLink,';
echo '							"desc": window.shareData.tContent,';
echo '							"title": window.shareData.tTitle';
echo '						}, function (res) {';
echo '							/* _report(\'timeline\', res.err_msg); */';
echo '						});';
echo '					});';
echo '					/* 分享到微博 */';
echo '					WeixinJSBridge.on(\'menu:share:weibo\', function (argv) {';
echo '						WeixinJSBridge.invoke(\'shareWeibo\', {';
echo '							"content": window.shareData.wContent,';
echo '							"url": window.shareData.weiboLink,';
echo '						}, function (res) {';
echo '							/* _report(\'weibo\', res.err_msg); */';
echo '						});';
echo '					});';
echo '				}, false);';
echo '			document.write(\'<scr\'+\'ipt type="text/javascript" src="js/zepto.min.js?v=\'+Date.now()+\'"></scr\'+\'ipt>\');';
echo '		  	document.write(\'<scr\' + \'ipt type="text/javascript" src="js/download.min.js?v=\'+Date.now()+\'"></scr\' + \'ipt>\');';
echo '		</script>';
echo '	</body>';
echo '</html>';

?>